### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by Joeyh021** [UWCS/rs118-chip8#1]
While sound looks like it is meant to exist/work, there's currently nothing implemented in `cpu::Cpu::run` to handle it. I tried doing it using [Rodio](https://github.com/RustAudio/rodio) but had no luck. May have to do it directly using [Cpal](https://github.com/RustAudio/cpal), or give Rodio another try.

**Comment by ericthelemur** [comment]
Probably should test a little more, but idk what roms use sound, works for the audio test one tho

**Comment by ericthelemur** [comment]
Turns out pong has sound, and that works properly. looks like this is good then
